// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0UBaXWI3Q3FrJjhNRs5glB5h0YFQiqwA',
    appId: '1:30890217547:web:59eca6c677fb9eeb61bdce',
    messagingSenderId: '30890217547',
    projectId: 'chat-app-eccfd',
    authDomain: 'chat-app-eccfd.firebaseapp.com',
    storageBucket: 'chat-app-eccfd.appspot.com',
    measurementId: 'G-HSY5Y5DC4H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3h3Y7GCtY4wKqTvsTiOZEfCzRPT_yhfI',
    appId: '1:30890217547:android:d17566f9b893f1a361bdce',
    messagingSenderId: '30890217547',
    projectId: 'chat-app-eccfd',
    storageBucket: 'chat-app-eccfd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRQFq-ylXUa4j0TiNk5LsYukONFSsOmQ0',
    appId: '1:30890217547:ios:867301f0f971b71f61bdce',
    messagingSenderId: '30890217547',
    projectId: 'chat-app-eccfd',
    storageBucket: 'chat-app-eccfd.appspot.com',
    iosClientId: '30890217547-mdf1ae3hl0u0vs3hf6j0gsd5tvg2vcvg.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRQFq-ylXUa4j0TiNk5LsYukONFSsOmQ0',
    appId: '1:30890217547:ios:867301f0f971b71f61bdce',
    messagingSenderId: '30890217547',
    projectId: 'chat-app-eccfd',
    storageBucket: 'chat-app-eccfd.appspot.com',
    iosClientId: '30890217547-mdf1ae3hl0u0vs3hf6j0gsd5tvg2vcvg.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );
}
